### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by mika76** [multiplex/multiplex.js#1]
I'd love to see some benchmarks and how this compares to other js libraries like lodash, underscore, lazy, jlinq, etc...

**Comment by KamyarNazeri** [comment]
@mika76  By design we have paid a great deal to performance of multiplex, I'm happy to share the benchmarks associated with assessing performance characteristics of multiplex and comparison with other js libraries once the documentation is finished. 
Hopefully it makes it through with the release of version 1.0

**Comment by KamyarNazeri** [comment]
@mika76 [here at jsPerf](http://jsperf.com/multiplex/6) you can find some raw performance comparison between `multiplex`, `lodash`, `lazy` and `linq.js`.
Multiplex is most of the time faster than the other libraries, in `sum`, `intersect`, `distinct` and `any` operators.
[any operator](http://jsperf.com/multiplex/6)
[intersect operator](http://jsperf.com/multiplex/5)
[distinct operator](http://jsperf.com/multiplex/4)
[sum operator](http://jsperf.com/multiplex/3)

**Comment by KamyarNazeri** [comment]
Benchmarks are available upon completion of Version 2.0.0
-Version 2.0 is going to be written from ground-up in two separate branches: ES6 which is up to the latest standard of ECMA (including classes, generators, symbols, spread operator, destructuring,...) and does not support backward compatibility, and ES5 which also benefits from the ES6 standard but is fully backward compatible.		
 -We try our best not to include breaking changes to the API, however, should any new feature is irreversible, we provide a list of breaking changes in the wiki section.		
 -Keep in mind that the master branch in under development and might be broken, is you wish to fork a stable branch please refer to 'release-1.0' which is already locked for this purpose.
