### ISSUE TITLE
count returns unexpected value with an object array.

### ISSUE THREAD

**Issue by narrowizard** [multiplex/multiplex.js#28]
i have an object array ` [{ Expression: "model" }, { Expression: "data" }]` and i use mx to count the predicated items. 

here is my code:  
```js
var data = [{ Expression: "model" }, { Expression: "data" }];
var c = mx(data).where(function (it) { return it.Expression == "data" }).count();
console.log(c);
```
it expected that c is 1,but got zero. the following code doesn't works either.

```js
var data = [{ Expression: "model" }, { Expression: "data" }];
var c = mx(data).where(function (it) { return mx.equals(it.Expression, "data") }).count();
console.log(c);
```

is there any mistakes in my code?

**Comment by KamyarNazeri** [comment]
@narrowizard Thank you for your input.
Your code is just fine, there's a bug in the `whereIterator` module that breaks the iterator chain once the predicate returns false.
I have already fixed it, but keep in mind that the code is not yet finalized and some errors might happen. Please send feedbacks if you encounter any bugs.

**Comment by narrowizard** [comment]
@KamyarNazeri  
i have tested the new publishment, and it works well. 
thank you for your fixing.
