### ISSUE TITLE
GroupBy passes the group as the resultSelector value, instead of the group.elements

### ISSUE THREAD

**Issue by patroza** [multiplex/multiplex.js#29]
`value: resultSelector ? resultSelector(next.value.key, next.value) : next.value,`
should be
`value: resultSelector ? resultSelector(next.value.key, next.value.elements) : next.value,`

According to the [LINQ spec](https://msdn.microsoft.com/en-us/library/bb549393(v=vs.110).aspx) and [multiplex.d.ts](https://github.com/multiplex/multiplex.js/blob/master/src/typings/multiplex.d.ts#L1832)

**Comment by KamyarNazeri** [comment]
@patroza This is actually a reminder to complete the unit tests! It's already 74% covered, but then again, you could easily miss these bugs! 😄

**Comment by KamyarNazeri** [comment]
@patroza To be fair, LINQ spec does not say anything about the second argument of the `resultSelector` other than it being of type `IEnumerable<TSource>`. The `Grouping` type *is* extends Iterable, so the spec is met. 

That being said, I changed the implementation to accept an `Iterable` object.
