### ISSUE TITLE
it causes infinite loop when i test join method

### ISSUE THREAD

**Issue by narrowizard** [multiplex/multiplex.js#36]
## Test Code
it causes infinite loop when i test join method with below code.  
```js
var data1 = [28, 26, 25, 24, 23, 21, 20, 19, 18, 16];

var data2 = [1, 2, 3, 4, 5, 6, 7, 8];
var data3 = mx(data1).join(data2, it => it, it => it, (a, b) => {
    return {
        Id: a
    }
}).toArray();
console.log(data3);
```

**Comment by narrowizard** [comment]
## Debug
the infinite loop is triggered at LookupTable.getGrouping method while finding the key of 23.
![image](https://user-images.githubusercontent.com/11383928/28599842-66a332ce-71e0-11e7-884c-c5c3892c7cb7.png)
it begins with the index of 5 and this.slots[5].next is also 5.

**Comment by KamyarNazeri** [comment]
The problem is with the LookupTable's `resize` method! Which makes the `slots` point to themselves instead of the `next` item with the same hash code! This happens when the number of the items are more than the size of the `LookupTable` and it tries to resize!
